name: Build PDFs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Typst
      run: |
        sudo apt update
        sudo apt install -y cargo
        cargo install typst-cli
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
    - name: Setup fonts and compile PDFs
      run: |
        chmod +x build.sh
        ./build.sh all
        
    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdfs
        path: output/*.pdf
        retention-days: 30